name: 'Version Bump for Node'
description: 'Updates the version of package.json and package-lock.json'
inputs:
  new-version:
    description: 'This is the new version if non is added we will bump the last one.'
    required: false
    default: null
outputs:
  old-version:
    description: 'This is the old version if non is added we will bump the last one.'
runs:
  using: 'node12'
  main: 'index.js'